### ISSUE TITLE
Cannot read property 'forEach' of undefined on every route change

### ISSUE THREAD

**Issue by lukepighetti** [preactjs/preact-router#343]
I have a fairly underwhelming router setup

```
export default class App extends Component {
  render() {
    return (
      <Router>
        <HomeView path="/" data={require("../stubs/home.json")} />
        <Login
          path="/login"
          isLoggedIn={isLoggedIn}
          onLoginSuccess={() => route("/settings", true)}
          onLoginFailure={() => route("/", true)}
        />
        <Logout path="/logout" onLogoutSuccess={() => route("/", true)} />
        <SettingsView
          path="/settings"
          api={api}
          data={require("../stubs/settings.json")}
        />
      </Router>
    );
  }
}
```

And every time I navigate to a new route I get this error in latest Chrome.

<img width="620" alt="Screen Shot 2019-11-03 at 5 13 20 PM" src="https://user-images.githubusercontent.com/666539/68092870-a7138a00-fe5d-11e9-840e-892c6619a515.png">

Break location

<img width="1484" alt="Screen Shot 2019-11-03 at 5 13 02 PM" src="https://user-images.githubusercontent.com/666539/68092873-ac70d480-fe5d-11e9-9eb9-f2d4f735dfbb.png">

The error + break seem to be very unhelpful. I'd love to provide more details but I'm not sure how to figure out more about what's going on. Any suggestions?

**Comment by andrewiggins** [comment]
Hey @lukepighetti Hmmm that is a weird error. What versions of `preact` and `preact-router` are you using? Are you using `preact/compat` or `preact/hooks`? The error reminds me of a bug we fixed in preact version 10.0.4. If you aren't using that version, could you try upgrading to that one?

Also, if you have a full repro you can share (e.g. in a codesandbox) that might help us narrow down the cause. I tried to build one [here](https://codesandbox.io/s/preact-router343-fnvrp) but it didn't repro :/

**Comment by marvinhagemeister** [comment]
Another shot in the dark: Maybe you're have a wrong import somewhere like `preact/hooks/src` instead of `preact/hooks`.

**Comment by lukepighetti** [comment]
Upgraded to `10.0.4` and it appears to have been resolved. Will reopen if I run into it again. Thank you.
