### ISSUE TITLE
activeClassName with class and className for Link 

### ISSUE THREAD

**Issue by rwhendry** [preactjs/preact-router#365]
I find something interseting in the Link Component with the activeClassName

```jsx
  <Link href="/" activeClassName="active" className="className"/>
```
if the match route it will give the <a> only the "className" class but if i change it to this
```jsx
  <Link href="/" activeClassName="active" class="className"/>
```
then it will give the <a> "className" and "active" as its class. 

Is this intended?

**Comment by developit** [comment]
This is intended. `preact-router` is designed for use with Preact, which means it expects a `class` prop, not `className`.

**Comment by evenfrost** [comment]
@developit according to your [comment](https://github.com/preactjs/preact/issues/103#issuecomment-199890596), it is possible and allowed to use both `class` and `className` in Preact. In my own case, I'm using `className` everywhere just because I have separate projects on React and don't want to have issues memorizing the proper syntax when switching between them.

Why just don't support both? And following this logic, the active class should be named `activeClass`, not `activeClassName` then.

**Comment by developit** [comment]
@evenfrost TBH you're right, there's not really a good reason for preact-router should take a stance on this. I've opened #386 that implements both your suggestions (`className` support as well as `activeClass`). Thanks for the nudge!
