### ISSUE TITLE
unable to use hooks

### ISSUE THREAD

**Issue by Th0rgal** [preactjs/preact-router#375]
Hello,

When I'm using a component my page is working:
source code:
https://github.com/cashplace/client/blob/3317123348ca253b7d378ff0918179d93b386888/cashplace/src/routes/ticket/index.js

But when I'm using a hook, I have an error:
source code:
https://github.com/cashplace/client/blob/d4c4b44c519f7fbbd74547ae044fa9442fd230ff/cashplace/src/routes/ticket/index.js

error:
![error](https://media.discordapp.net/attachments/216216713711190016/743077572698439722/unknown.png)

I'm using it that way:
```jsx
  render() {
    return (
      <div id="app">
        <Header />
        <Router onChange={this.handleRoute}>
          <Home path="/" requestsManager={this.state.requestsManager} />
          <Ticket path="/:id" requestsManager={this.state.requestsManager} />
        </Router>
      </div>
    );
  }
```

I'm not sure from where this issue comes from. If I didn't open this issue in the right place please tell it to me.
Any help is appreciated!

**Comment by lightdiscord** [comment]
When you import `useParams` from `preact-router` [here](https://github.com/cashplace/client/blob/d4c4b44c519f7fbbd74547ae044fa9442fd230ff/cashplace/src/routes/ticket/index.js#L2) there are multiple problems.
* First, you import the default export of `preact-router` rather than an export called `useParams`.
* Second, unlike `react-router` there are no `useParams` hook. With `preact-router` [any url parameter is passed to the component as a `props`](https://github.com/preactjs/preact-router/blob/master/README.md#handling-urls). So you may want to remove the import and [this line](https://github.com/cashplace/client/blob/d4c4b44c519f7fbbd74547ae044fa9442fd230ff/cashplace/src/routes/ticket/index.js#L6) and replace [this line](https://github.com/cashplace/client/blob/d4c4b44c519f7fbbd74547ae044fa9442fd230ff/cashplace/src/routes/ticket/index.js#L5) with
```js
export default function Ticket({ requestsManager, id }) {
    // ...
}
```
