### ISSUE TITLE
'Router' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by ljmerza** [preactjs/preact-router#426]
when trying to build i get

```
src/app.tsx:29:10 - error TS2786: 'Router' cannot be used as a JSX component.
  Its instance type 'Router' is not a valid JSX element.
    Property 'refs' is missing in type 'Router' but required in type 'ElementClass'.

29         <Router>
```

**Comment by codepunkt** [comment]
Same here, using `preact-router@4.1.0` and `preact@10.10.0`

**Comment by inferusvv** [comment]
Just add this to your `tsconfig.json`

```
// TypeScript >= 4.1.1
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "preact",
    //...
  }
}
```

Described here: https://preactjs.com/guide/v10/typescript/#typescript-configuration

**Comment by rschristian** [comment]
Can't reproduce, might've been a TS issue?

Going to close out, feel free to reply with more info if it's still an issue.

**Comment by EquinoxFlowerJG** [comment]
Have you solved this problem?

**Comment by inferusvv** [comment]
> Have you solved this problem?

My solution didn't help? https://github.com/preactjs/preact-router/issues/426#issuecomment-1398645009

**Comment by EquinoxFlowerJG** [comment]
> > Have you solved this problem?
> 
> My solution didn't help? [#426 (comment)](https://github.com/preactjs/preact-router/issues/426#issuecomment-1398645009)

I have added that in my `tsconfig.json` before. But it still can not work. 
Then, I found that the default exported Router is indeed not a JSX component. I changed the `import Router from 'preact-router';` to `import { Router } from 'preact-router';` because the useage example in [README.md](https://github.com/preactjs/preact-router#readme) do that sometimes.
In fact, both of these ways are used in the README.md, which makes me very confused. There are still many areas in the README.md that confuse me, not just this one.

**Comment by inferusvv** [comment]
>  There are still many areas in the README.md that confuse me, not just this one.

This is preact 😄

It is not well supported in my opinion, so I've decided to pick another solution after some time.

**Comment by Luk139** [comment]
{/* @ts-expect-error Server Component */}
{/* @ts-expect-error */}

Weirdly enough, copying either of those in the line before the component that throws the error, seems to fix the Problem for now. Remove the {} if you are inside a return, so just /* @ts-expect-error */
