### ISSUE TITLE
Unwanted css files are shared between multiple routes

### ISSUE THREAD

**Issue by MiftikCZ** [preactjs/preact-router#442]
## first route
- loads up `first.css` corectlly just for the first route
```tsx
import "./first.css"

export default function({}) {
  return <>
     ... some code here
  </>
}
```

## second route
- loads up empty `second.css` file (which is correct)
- **so the second route should be without styling BUT it has the styles from the first route (the `first.css`)**
```tsx
import "./second.css"

export default function({}) {
  return <>
     ... some code here for the second route
  </>
}
```

## app.tsx
- my app.tsx
```tsx
import { render } from 'preact'
import { Router } from 'preact-router';
import App from './pages/first.tsx';
import Main from './pages/second.tsx';

import './index.css'
import "@fontsource/fira-sans"

render((
    <Router>
        <App key="app" path="/" />
        <Main key="main" path="/main" />
    </Router>
), document.getElementById('app') as HTMLElement)
```

**Comment by marvinhagemeister** [comment]
The `preact-router` package is a client side routing library. It looks and works with the `history` API matches what route the user is on. Because of that it has no knowledge of how you're authoring the application. It sounds like you're expecting assets to be loaded and discarded for the current route. That's functionality that is typically provided by the meta-framework or preset you're using to build your application. These know how you authored your code and can rewrite it accordingly. Posting the question there might yield more answers.
